services:
  prisma-migrate:
    build:
      dockerfile: dockerfile
      context: .
    env_file:
        - .env
    command: npm run migrate
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
  api:
    build:
      dockerfile: dockerfile
      context: .
    env_file:
        - .env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000

  